import { join, relative } from 'node:path';
import { safeWriteFile } from '../utils/fs-helpers.js';
import { logger } from '../utils/logger.js';
import type { ManifestInfo, ApkMeta } from '../core/apk-parser.js';
import type { ScanResult } from '../core/scanner.js';
import type { MappedEndpoint } from '../core/endpoint-mapper.js';
import type { DecompileResult } from '../core/decompiler.js';

/** All data needed to generate a Markdown report */
export interface ReportData {
  manifest: ManifestInfo;
  meta: ApkMeta;
  scanResult: ScanResult;
  mappedEndpoints: MappedEndpoint[];
  decompileResult?: DecompileResult;
  generatedAt?: string;
}

/**
 * Generate a comprehensive Markdown analysis report from pipeline outputs.
 */
export function generateMarkdownReport(data: ReportData): string {
  const { manifest, meta, scanResult, mappedEndpoints, decompileResult } = data;
  const timestamp = data.generatedAt ?? new Date().toISOString();
  const lines: string[] = [];

  const push = (...text: string[]) => lines.push(...text);

  // ── Header ──
  push(
    `# APK Analysis Report`,
    '',
    `> Generated by [apk-archeologist](https://github.com/apk-archeologist) on ${timestamp}`,
    '',
    '---',
    '',
  );

  // ── Game Metadata ──
  push('## Game Metadata', '');
  push('| Field | Value |');
  push('|-------|-------|');
  push(`| Package | \`${manifest.packageName}\` |`);
  push(`| Version | ${manifest.versionName} (code ${manifest.versionCode}) |`);
  push(`| Min SDK | ${manifest.minSdkVersion} |`);
  push(`| Target SDK | ${manifest.targetSdkVersion} |`);
  push(`| Engine | ${formatEngine(meta.engine)} |`);
  push(`| Input Type | ${meta.inputType} |`);
  push(`| SHA-256 | \`${meta.sha256}\` |`);
  push('');

  // ── Permissions ──
  if (manifest.permissions.length > 0) {
    push('## Permissions', '');
    for (const perm of manifest.permissions) {
      const short = perm.replace('android.permission.', '');
      push(`- \`${short}\``);
    }
    push('');
  }

  // ── Components ──
  const componentSections = [
    { title: 'Activities', items: manifest.activities },
    { title: 'Services', items: manifest.services },
    { title: 'Content Providers', items: manifest.contentProviders },
    { title: 'Broadcast Receivers', items: manifest.receivers },
  ];

  const hasComponents = componentSections.some((s) => s.items.length > 0);
  if (hasComponents) {
    push('## Application Components', '');
    for (const section of componentSections) {
      if (section.items.length > 0) {
        push(`### ${section.title}`, '');
        for (const item of section.items) {
          push(`- \`${item}\``);
        }
        push('');
      }
    }
  }

  // ── Native Libraries ──
  if (meta.nativeLibs.length > 0) {
    push('## Native Libraries', '');
    push('| Library | ABI |');
    push('|---------|-----|');
    for (const lib of meta.nativeLibs) {
      push(`| \`${lib.name}\` | ${lib.abi} |`);
    }
    push('');
  }

  // ── Engine Details ──
  if (meta.engine !== 'native') {
    push('## Engine Details', '');
    push(`- **Engine**: ${formatEngine(meta.engine)}`);
    push(`- **Global Metadata**: ${meta.hasGlobalMetadata ? 'Yes (IL2CPP)' : 'No'}`);
    push(`- **Managed DLLs**: ${meta.hasManagedDlls ? 'Yes (Mono)' : 'No'}`);
    push('');
  }

  // ── Decompilation Results ──
  if (decompileResult) {
    push('## Decompilation Results', '');
    push('| Tool | Status | Duration |');
    push('|------|--------|----------|');
    if (decompileResult.jadx) {
      const r = decompileResult.jadx;
      push(`| JADX | ${r.success ? '✅ Success' : '❌ Failed'} | ${(r.duration / 1000).toFixed(1)}s |`);
    }
    if (decompileResult.assetRipper) {
      const r = decompileResult.assetRipper;
      push(`| AssetRipper | ${r.success ? '✅ Success' : '❌ Failed'} | ${(r.duration / 1000).toFixed(1)}s |`);
    }
    if (decompileResult.il2cppDumper) {
      const r = decompileResult.il2cppDumper;
      push(`| Il2CppDumper | ${r.success ? '✅ Success' : '❌ Failed'} | ${(r.duration / 1000).toFixed(1)}s |`);
    }
    push('');
  }

  // ── Scan Summary ──
  push('## Network Analysis Summary', '');
  push('| Metric | Count |');
  push('|--------|-------|');
  push(`| Files scanned | ${scanResult.summary.filesScanned} / ${scanResult.summary.totalFiles} |`);
  push(`| URLs discovered | ${scanResult.summary.urlsFound} |`);
  push(`| Unique endpoints | ${scanResult.summary.endpointsFound} |`);
  push(`| Auth patterns | ${scanResult.summary.authPatternsFound} |`);
  push('');

  if (Object.keys(scanResult.summary.categories).length > 0) {
    push('### Endpoint Categories', '');
    push('| Category | Count |');
    push('|----------|-------|');
    for (const [cat, count] of Object.entries(scanResult.summary.categories).sort(([, a], [, b]) => b - a)) {
      push(`| ${cat} | ${count} |`);
    }
    push('');
  }

  // ── Discovered URLs ──
  if (scanResult.urls.length > 0) {
    push('## Discovered URLs', '');
    // Group by category
    const byCategory = groupBy(scanResult.urls, (u) => u.category);
    for (const [cat, urls] of Object.entries(byCategory)) {
      push(`### ${capitalize(cat)}`, '');
      for (const u of urls) {
        push(`- \`${u.url}\``);
        push(`  - File: \`${u.file}\` (line ${u.line})`);
      }
      push('');
    }
  }

  // ── Endpoint Catalog ──
  if (mappedEndpoints.length > 0) {
    push('## Endpoint Catalog', '');
    push('| # | Method | Path | Category | Sources |');
    push('|---|--------|------|----------|---------|');
    mappedEndpoints.forEach((ep, i) => {
      const methodBadge = ep.method === 'UNKNOWN' ? '?' : ep.method;
      push(`| ${i + 1} | \`${methodBadge}\` | \`${ep.path}\` | ${ep.category} | ${ep.sources.length} |`);
    });
    push('');

    // Detailed endpoint info
    push('### Endpoint Details', '');
    for (const ep of mappedEndpoints) {
      push(`#### \`${ep.method === 'UNKNOWN' ? '?' : ep.method} ${ep.path}\``, '');
      push(`- **Category**: ${ep.category}`);
      if (ep.fullUrl) push(`- **Full URL**: \`${ep.fullUrl}\``);
      if (ep.parameters.length > 0) {
        push(`- **Parameters**: ${ep.parameters.map((p) => `\`${p.name}\` (${p.location})`).join(', ')}`);
      }
      push(`- **Found in**:`);
      for (const src of ep.sources.slice(0, 5)) {
        push(`  - \`${src.file}\` line ${src.line}`);
      }
      if (ep.sources.length > 5) {
        push(`  - ... and ${ep.sources.length - 5} more`);
      }
      push('');
    }
  }

  // ── Auth Flow ──
  if (scanResult.authPatterns.length > 0) {
    push('## Authentication Patterns', '');
    const byType = groupBy(scanResult.authPatterns, (p) => p.type);
    for (const [type, patterns] of Object.entries(byType)) {
      push(`### ${capitalize(type)}`, '');
      for (const p of patterns.slice(0, 10)) {
        push(`- \`${p.file}\` line ${p.line}`);
        push(`  \`\`\`${p.context}\`\`\``);
      }
      if (patterns.length > 10) {
        push(`- ... and ${patterns.length - 10} more occurrences`);
      }
      push('');
    }
  }

  // ── Preservation Notes ──
  push('## Preservation Notes', '');
  push(generatePreservationNotes(meta, scanResult, mappedEndpoints));
  push('');

  // ── Footer ──
  push(
    '---',
    '',
    '*This report was automatically generated. Manual review is recommended for accuracy.*',
  );

  return lines.join('\n');
}

/**
 * Generate context-specific preservation advice based on analysis results.
 */
function generatePreservationNotes(meta: ApkMeta, scan: ScanResult, endpoints: MappedEndpoint[]): string {
  const notes: string[] = [];

  // Engine-specific advice
  switch (meta.engine) {
    case 'unity-mono':
      notes.push('- **Unity Mono build detected.** Full C# source recovery should be possible via AssetRipper. This is the best-case scenario for preservation.');
      break;
    case 'unity-il2cpp':
      notes.push('- **Unity IL2CPP build detected.** C# source recovery will be partial (stubs + string literals). Consider finding an older Mono build of the same game for better results.');
      break;
    case 'unreal':
      notes.push('- **Unreal Engine detected.** Unreal APK analysis is planned for a future version.');
      break;
    case 'godot':
      notes.push('- **Godot Engine detected.** Godot analysis is planned for a future version.');
      break;
    default:
      notes.push('- **Native Java/Kotlin app.** JADX should provide good source recovery.');
  }

  // Auth chain priority
  const authEndpoints = endpoints.filter((ep) => ep.category === 'auth');
  if (authEndpoints.length > 0) {
    notes.push(`- **${authEndpoints.length} auth endpoint(s) detected.** These are high priority for mock server implementation — the game likely won't get past the loading screen without a working auth chain.`);
  }

  // CDN warning
  const cdnUrls = scan.urls.filter((u) => u.category === 'cdn');
  if (cdnUrls.length > 0) {
    notes.push(`- **${cdnUrls.length} CDN URL(s) found.** CDN servers are often decommissioned before game APIs. Prioritize mirroring asset bundle downloads if the game is still live.`);
  }

  // Warning about app data
  notes.push('- **⚠️ Do not clear app data** (`pm clear`) if the game\'s CDN is already offline. Cached assets on the device may be irreplaceable.');

  if (scan.authPatterns.some((p) => p.type === 'jwt')) {
    notes.push('- **JWT authentication detected.** The mock server should implement JWT token issuance and validation.');
  }

  return notes.join('\n');
}

/**
 * Write the Markdown report to disk.
 */
export async function writeMarkdownReport(workdir: string, data: ReportData): Promise<string> {
  const content = generateMarkdownReport(data);
  const reportPath = join(workdir, 'analysis', 'report.md');
  await safeWriteFile(reportPath, content);
  logger.success(`Markdown report written to ${relative(workdir, reportPath)}`);
  return reportPath;
}

// ── Helpers ──

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function groupBy<T>(items: T[], key: (item: T) => string): Record<string, T[]> {
  const groups: Record<string, T[]> = {};
  for (const item of items) {
    const k = key(item);
    (groups[k] ??= []).push(item);
  }
  return groups;
}

function formatEngine(engine: string): string {
  const names: Record<string, string> = {
    'unity-mono': 'Unity (Mono)',
    'unity-il2cpp': 'Unity (IL2CPP)',
    unreal: 'Unreal Engine',
    godot: 'Godot',
    native: 'Native Java/Kotlin',
  };
  return names[engine] ?? engine;
}
