import { join, relative, extname } from 'node:path';
import { readdir, readFile, stat } from 'node:fs/promises';
import { safeWriteFile } from '../utils/fs-helpers.js';
import { logger } from '../utils/logger.js';

// ────────────────────────────────────────────
// Types
// ────────────────────────────────────────────

export interface CompareResult {
  originalDir: string;
  reconstructedDir: string;
  originalFileCount: number;
  reconstructedFileCount: number;
  matchedFiles: FileMatch[];
  unmatchedOriginal: string[];
  unmatchedReconstructed: string[];
  overallSimilarity: number;
}

export interface FileMatch {
  originalPath: string;
  reconstructedPath: string;
  similarity: number;
  originalLines: number;
  reconstructedLines: number;
  sharedSymbols: string[];
}

// ────────────────────────────────────────────
// Main entry point
// ────────────────────────────────────────────

export async function compareSources(
  originalDir: string,
  reconstructedDir: string,
): Promise<CompareResult> {
  logger.info('Collecting source files...');
  const originalFiles = await collectSourceFiles(originalDir);
  const reconstructedFiles = await collectSourceFiles(reconstructedDir);

  logger.info(`Original: ${originalFiles.length} files, Reconstructed: ${reconstructedFiles.length} files`);

  // Match files by class name
  const matches: FileMatch[] = [];
  const matchedOriginal = new Set<string>();
  const matchedReconstructed = new Set<string>();

  for (const origFile of originalFiles) {
    const origName = fileBaseName(origFile);
    const origContent = await readFile(join(originalDir, origFile), 'utf-8');

    for (const reconFile of reconstructedFiles) {
      const reconName = fileBaseName(reconFile);

      // Match on filename (class name)
      if (origName === reconName) {
        const reconContent = await readFile(join(reconstructedDir, reconFile), 'utf-8');
        const similarity = computeSimilarity(origContent, reconContent);
        const sharedSymbols = findSharedSymbols(origContent, reconContent);

        matches.push({
          originalPath: origFile,
          reconstructedPath: reconFile,
          similarity,
          originalLines: origContent.split('\n').length,
          reconstructedLines: reconContent.split('\n').length,
          sharedSymbols,
        });

        matchedOriginal.add(origFile);
        matchedReconstructed.add(reconFile);
        break;
      }
    }
  }

  const unmatchedOriginal = originalFiles.filter((f) => !matchedOriginal.has(f));
  const unmatchedReconstructed = reconstructedFiles.filter((f) => !matchedReconstructed.has(f));

  const overallSimilarity =
    matches.length > 0
      ? Math.round(matches.reduce((sum, m) => sum + m.similarity, 0) / matches.length)
      : 0;

  return {
    originalDir,
    reconstructedDir,
    originalFileCount: originalFiles.length,
    reconstructedFileCount: reconstructedFiles.length,
    matchedFiles: matches,
    unmatchedOriginal,
    unmatchedReconstructed,
    overallSimilarity,
  };
}

export async function writeCompareReport(outputPath: string, result: CompareResult): Promise<void> {
  const lines: string[] = [];

  lines.push('# Source Comparison Report');
  lines.push('');
  lines.push(`> Generated by apk-archeologist on ${new Date().toISOString()}`);
  lines.push('');

  lines.push('## Overview');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Original files | ${result.originalFileCount} |`);
  lines.push(`| Reconstructed files | ${result.reconstructedFileCount} |`);
  lines.push(`| Matched pairs | ${result.matchedFiles.length} |`);
  lines.push(`| Unmatched (original) | ${result.unmatchedOriginal.length} |`);
  lines.push(`| Unmatched (reconstructed) | ${result.unmatchedReconstructed.length} |`);
  lines.push(`| **Overall similarity** | **${result.overallSimilarity}%** |`);
  lines.push('');

  if (result.matchedFiles.length > 0) {
    lines.push('## File Matches');
    lines.push('');
    lines.push('| Original | Reconstructed | Similarity | Orig Lines | Recon Lines | Shared Symbols |');
    lines.push('|----------|---------------|------------|------------|-------------|----------------|');
    for (const match of result.matchedFiles) {
      lines.push(
        `| ${match.originalPath} | ${match.reconstructedPath} | ${match.similarity}% | ${match.originalLines} | ${match.reconstructedLines} | ${match.sharedSymbols.length} |`,
      );
    }
    lines.push('');

    // Detailed per-file
    lines.push('## Detailed Comparisons');
    lines.push('');
    for (const match of result.matchedFiles) {
      lines.push(`### ${fileBaseName(match.originalPath)}`);
      lines.push('');
      lines.push(`- **Similarity:** ${match.similarity}%`);
      lines.push(`- **Original:** ${match.originalLines} lines → **Reconstructed:** ${match.reconstructedLines} lines`);
      if (match.sharedSymbols.length > 0) {
        lines.push(`- **Shared symbols:** \`${match.sharedSymbols.slice(0, 20).join('`, `')}\``);
      }
      lines.push('');

      const bar = renderBar(match.similarity);
      lines.push(`\`\`\`\n${bar}\n\`\`\``);
      lines.push('');
    }
  }

  if (result.unmatchedOriginal.length > 0) {
    lines.push('## Unmatched Original Files');
    lines.push('');
    lines.push('These files from the original source had no corresponding reconstructed file:');
    lines.push('');
    for (const f of result.unmatchedOriginal) {
      lines.push(`- ${f}`);
    }
    lines.push('');
  }

  if (result.unmatchedReconstructed.length > 0) {
    lines.push('## Unmatched Reconstructed Files');
    lines.push('');
    lines.push('These reconstructed files had no corresponding original:');
    lines.push('');
    for (const f of result.unmatchedReconstructed) {
      lines.push(`- ${f}`);
    }
    lines.push('');
  }

  await safeWriteFile(outputPath, lines.join('\n'));
}

// ────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────

async function collectSourceFiles(dir: string): Promise<string[]> {
  const files: string[] = [];
  await walkCollect(dir, dir, files);
  return files;
}

async function walkCollect(baseDir: string, currentDir: string, accumulator: string[]): Promise<void> {
  let entries;
  try {
    entries = await readdir(currentDir, { withFileTypes: true });
  } catch {
    return;
  }

  for (const entry of entries) {
    const fullPath = join(currentDir, entry.name);
    if (entry.isDirectory()) {
      await walkCollect(baseDir, fullPath, accumulator);
    } else if (entry.isFile()) {
      const ext = extname(entry.name).toLowerCase();
      if (['.java', '.kt', '.cs', '.xml', '.json'].includes(ext)) {
        accumulator.push(relative(baseDir, fullPath));
      }
    }
  }
}

function fileBaseName(filePath: string): string {
  const base = filePath.split(/[/\\]/).pop() ?? filePath;
  return base.replace(extname(base), '');
}

function computeSimilarity(a: string, b: string): number {
  const aTokens = tokenize(a);
  const bTokens = tokenize(b);

  if (aTokens.size === 0 && bTokens.size === 0) return 100;
  if (aTokens.size === 0 || bTokens.size === 0) return 0;

  let shared = 0;
  for (const token of aTokens) {
    if (bTokens.has(token)) shared++;
  }

  const union = new Set([...aTokens, ...bTokens]).size;
  return Math.round((shared / union) * 100);
}

function tokenize(content: string): Set<string> {
  // Extract identifiers >2 chars
  const matches = content.match(/\b[a-zA-Z_]\w{2,}\b/g);
  return new Set(matches ?? []);
}

function findSharedSymbols(a: string, b: string): string[] {
  const aSymbols = extractSymbols(a);
  const bSymbols = extractSymbols(b);
  const shared: string[] = [];

  for (const sym of aSymbols) {
    if (bSymbols.has(sym)) shared.push(sym);
  }

  return shared.sort();
}

function extractSymbols(content: string): Set<string> {
  const symbols = new Set<string>();

  // Class/method names
  const classRe = /(?:class|interface|enum)\s+(\w+)/g;
  let m;
  while ((m = classRe.exec(content)) !== null) symbols.add(m[1]);

  const methodRe = /(?:fun|void|int|boolean|String|float|double|long)\s+(\w+)\s*\(/g;
  while ((m = methodRe.exec(content)) !== null) symbols.add(m[1]);

  // Field/variable names
  const fieldRe = /(?:val|var|private|public|protected)\s+(?:\w+\s+)?(\w+)\s*[=:;]/g;
  while ((m = fieldRe.exec(content)) !== null) symbols.add(m[1]);

  // String constants (API paths etc.)
  const stringRe = /"(\/[\w/]+)"/g;
  while ((m = stringRe.exec(content)) !== null) symbols.add(m[1]);

  return symbols;
}

function renderBar(percent: number): string {
  const width = 40;
  const filled = Math.round((percent / 100) * width);
  const empty = width - filled;
  const bar = '█'.repeat(filled) + '░'.repeat(empty);
  return `[${bar}] ${percent}%`;
}
